
-- =============================================
-- 放射科工作量统计系统 - 数据库初始化脚本
-- =============================================
-- 执行顺序: 1.CreateTables.sql -> 2.CreateProcedures.sql -> 3.InitialData.sql

-- =============================================
-- 步骤1: 创建数据表
-- =============================================

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'EXAM_WORKLOAD_STAT')
BEGIN
    CREATE TABLE EXAM_WORKLOAD_STAT (
        ID INT PRIMARY KEY IDENTITY(1,1),
        STAT_DATE DATE NOT NULL,
        SYSTEM_SOURCE_NO VARCHAR(20) NOT NULL,
        SYSTEM_NAME VARCHAR(50),
        EXAM_CATEGORY_NAME VARCHAR(100),
        EXEC_DEPT_NAME VARCHAR(100),
        REPORTER_NAME VARCHAR(50),
        REVIEWER_NAME VARCHAR(50),
        TECHNICIAN_NAME VARCHAR(50),
        ENCOUNTER_TYPE_NO VARCHAR(20),
        ENCOUNTER_TYPE_NAME VARCHAR(50),
        NEG_POS_CODE VARCHAR(20),
        NEG_POS_NAME VARCHAR(20),
        TASK_COUNT INT DEFAULT 0,
        POSITIVE_COUNT INT DEFAULT 0,
        NEGATIVE_COUNT INT DEFAULT 0,
        POSITIVE_RATE DECIMAL(5,2),
        IS_DEL INT DEFAULT 0,
        CREATED_AT DATETIME DEFAULT GETDATE(),
        UPDATED_AT DATETIME
    );
    PRINT '表 EXAM_WORKLOAD_STAT 创建成功';
END
ELSE
BEGIN
    PRINT '表 EXAM_WORKLOAD_STAT 已存在';
END

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'EXAM_WORKLOAD_CONFIG')
BEGIN
    CREATE TABLE EXAM_WORKLOAD_CONFIG (
        ID INT PRIMARY KEY IDENTITY(1,1),
        CONFIG_KEY VARCHAR(50) UNIQUE NOT NULL,
        CONFIG_VALUE VARCHAR(500),
        CONFIG_DESC VARCHAR(200),
        IS_ACTIVE INT DEFAULT 1,
        CREATED_AT DATETIME DEFAULT GETDATE()
    );
    PRINT '表 EXAM_WORKLOAD_CONFIG 创建成功';
END
ELSE
BEGIN
    PRINT '表 EXAM_WORKLOAD_CONFIG 已存在';
END

-- =============================================
-- 创建索引
-- =============================================

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_EXAM_WORKLOAD_STAT_DATE')
BEGIN
    CREATE INDEX IX_EXAM_WORKLOAD_STAT_DATE ON EXAM_WORKLOAD_STAT(STAT_DATE);
    PRINT '索引 IX_EXAM_WORKLOAD_STAT_DATE 创建成功';
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_EXAM_WORKLOAD_SYSTEM')
BEGIN
    CREATE INDEX IX_EXAM_WORKLOAD_SYSTEM ON EXAM_WORKLOAD_STAT(SYSTEM_SOURCE_NO);
    PRINT '索引 IX_EXAM_WORKLOAD_SYSTEM 创建成功';
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_EXAM_WORKLOAD_DEPT')
BEGIN
    CREATE INDEX IX_EXAM_WORKLOAD_DEPT ON EXAM_WORKLOAD_STAT(EXEC_DEPT_NAME);
    PRINT '索引 IX_EXAM_WORKLOAD_DEPT 创建成功';
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_EXAM_WORKLOAD_REPORTER')
BEGIN
    CREATE INDEX IX_EXAM_WORKLOAD_REPORTER ON EXAM_WORKLOAD_STAT(REPORTER_NAME);
    PRINT '索引 IX_EXAM_WORKLOAD_REPORTER 创建成功';
END

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE name = 'IX_EXAM_WORKLOAD_ISDEL')
BEGIN
    CREATE INDEX IX_EXAM_WORKLOAD_ISDEL ON EXAM_WORKLOAD_STAT(IS_DEL);
    PRINT '索引 IX_EXAM_WORKLOAD_ISDEL 创建成功';
END

PRINT '=============================================';
PRINT '数据表创建完成';
PRINT '=============================================';
GO